
research_specialist:
  name: Research Specialist
  type: human
  description: Human expert in research and analysis
  capabilities:
  - research
  - analysis
  - reporting
  max_concurrent_tasks: 3
  is_available: true
  contact_method: slack
  contact_details:
    channel: '#research-team'
    user: '@researcher'
  model_name: null
  prompt_signature: null
  thread_id: null
  created_at: '2025-08-17T21:31:31.123456'
  last_active: null
sales_manager:
  name: Sales Manager
  type: human
  description: Human sales manager for deal management
  capabilities:
  - sales
  - crm
  - customer_relations
  max_concurrent_tasks: 3
  is_available: true
  contact_method: close_crm
  contact_details:
    user_id: sales_manager_001
  model_name: null
  prompt_signature: null
  thread_id: null
  created_at: '2025-08-17T21:31:31.123456'
  last_active: null
data_analyst:
  name: Data Analyst Agent
  type: agentic
  description: Autonomous agent for data analysis tasks
  capabilities:
  - data_analysis
  - visualization
  - reporting
  max_concurrent_tasks: 3
  is_available: true
  contact_method: null
  contact_details: null
  model_name: gpt-4
  prompt_signature: data_analysis_react
  thread_id: null
  created_at: '2025-08-17T21:31:31.123456'
  last_active: null
